version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
  commit-message:
      prefix: "chore(deps): update garden"
  assignees:
  - "dependabot[bot]"
  reviewers:
  - "hoanshiro"